In [1]:
from datetime import date
print(date.today())

2024-06-16


In [9]:
import time
# help(time)
print(time.strftime("%d/%m/%Y %H-%M-%S",time.localtime()))
print(time.strftime("%d/%m/%Y %I-%M-%S",time.localtime()))

16/06/2024 16-34-09
16/06/2024 04-34-09


In [10]:
import numpy as np

### Diff b/w Numpy Array and a list :
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

In [11]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [22]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(a))
print(a)
print(f"The elements at 0 index are ")
print(a[0])

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The elements at 0 index are 
[1 2 3]


In [23]:
print(np.zeros(3))

[0. 0. 0.]


In [24]:
print(np.ones(2))

[1. 1.]


In [31]:
# Create an empty array with 3 elements
print(np.empty(2))
print(np.empty(3))
print(np.empty(4))
# the elements inside the arrays may vary

[1. 1.]
[1.0862431e-311 1.0862431e-311 1.0862431e-311]
[0.0000000e+000 1.0862431e-311 1.0862431e-311 1.0862431e-311]


In [34]:
# arange
print(np.arange(10))
# The range starts from 0 and ends with range-1

[0 1 2 3 4 5 6 7 8 9]


In [39]:
# arange with step
# np.arange(start,end,step)
print(np.arange(2,21,2))
print(np.arange(1,21,2))

[ 2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [50]:
# linspace()
print(np.linspace(0, 10, num=2))
print(np.linspace(0, 10, num=5))
print(np.linspace(0, 10, num=3))
print(np.linspace(0, 10, 11))
print(type(np.linspace(0, 10, 11)))
'''here the linspace divides the interval into num equal sizes '''

[ 0. 10.]
[ 0.   2.5  5.   7.5 10. ]
[ 0.  5. 10.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


'here the linspace divides the interval into num equal sizes '

In [51]:
# sorting
print(np.sort([4,5,8,6,1,2,9,7,3]))

[1 2 3 4 5 6 7 8 9]


In [6]:
# Concatenate
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))


[1 2 3 4 5 6]


In [9]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x,y),axis=0))
# print(np.concatenate((x,y),axis=1))  --not possible because : 
# all the input array dimensions except for the concatenation axis must match exactly, 
# but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 11

[[1 2]
 [3 4]
 [5 6]]


In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[8,9]])
print(np.concatenate((x,y),axis=1)) 

[[1 2 5 6]
 [3 4 8 9]]


In [11]:
# dimensions --ndim
print(x.ndim)

2


In [12]:
# no of elements --size
print(x.size)

4


In [13]:
# shape
print(x.shape)

(2, 2)


In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [17]:
'''Multi dimensional array'''

'Multi dimensional array'

In [15]:
print(array_example.shape)

(3, 2, 4)


In [20]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
print(a.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
print(a.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
# Reshape
a=np.array([1,2,3,4])
print(a)

print(a.reshape(2,2))

[1 2 3 4]
[[1 2]
 [3 4]]


In [28]:
a=np.arange(12)
print(a)
print(a.reshape(4,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
