In [1]:
from datetime import date
print(date.today())

2024-06-18


### indexing and Slicing

In [6]:
import numpy as np
a= np.array([1,2,3,4,5,6])
print(a)
print(a[0])
print(a.shape)
print(((a[:,np.newaxis]).shape))
print(((a[:,np.newaxis])))
print(((a[np.newaxis])))

[1 2 3 4 5 6]
1
(6,)
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [7]:
print(a[0:2])

[1 2]


In [8]:
print(a[0:7])

[1 2 3 4 5 6]


In [9]:
print(a[:-1])

[1 2 3 4 5]


In [10]:
print(a[a>5])
print(a[a<5])
print(a[a%2==0])

[6]
[1 2 3 4]
[2 4 6]


In [13]:
# vstack and hstack
a1 = np.array([[1, 2],
               [3, 4]])

a2 = np.array([[5, 6],
               [7, 8]])
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [26]:
a=np.arange(21)
print(np.hsplit(a,3))
a=np.arange(21).reshape(3,7)
print(a)
print(np.vsplit(a,3))

[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18, 19, 20])]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[array([[0, 1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12, 13]]), array([[14, 15, 16, 17, 18, 19, 20]])]


In [27]:
a=np.arange(21)
b=a.copy()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [35]:
# Arithmetic operations using arrays
num= np.array([1,2,3])
one=np.ones(3)
print(num+one)

[2. 3. 4.]


In [36]:
num= np.array([1,2,3])
one=np.ones(3,dtype=int)
print(num+one)

[2 3 4]


In [37]:
a=np.arange(21)
print(a.sum())

210


In [44]:
a.reshape(3,7)
b=a.reshape(3,7).copy()
print(a)
print(b)
print(a.sum(axis=0))
print(b.sum(axis=1))
print(b.sum(axis=0))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
210
[ 21  70 119]
[21 24 27 30 33 36 39]


In [45]:
print(a.max())
print(a.min())

20
0


In [54]:
# Generating Random numbers
rng = np.random.default_rng()
print(rng.integers(10,size=(2,4)))

[[3 8 4 1]
 [0 4 1 2]]


In [55]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [57]:
# reverse array
print(np.flip(np.unique(a)))

[20 19 18 17 16 15 14 13 12 11]


In [59]:
'''You can save a NumPy array as a plain text file like a .csv or .txt file with np.savetxt'''
csv_arr=np.arange(30)
np.savetxt("newCSV.csv",csv_arr)
np.loadtxt('newCSV.csv')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [60]:
'''THis is the numpy i have learnt for 2day'''

'THis is the numpy i have learnt for 2day'